default: &default
  connection: 'amqp://guest:guest@localhost:5672' # TODO: Break these up?
  exchange: backlogg.api.comments
  queues:
    all: backlogg.api.comments.*
    create: backlogg.api.comments.create
    destroy: backlogg.api.comments.destroy
    index: backlogg.api.comments.index
    show: backlogg.api.comments.show
    update: backlogg.api.comments.update

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
